### ISSUE TITLE
Can't serve React static files

### ISSUE THREAD

**Issue by mendoza** [sindresorhus/electron-serve#16]
## Error
{ Error: ERR_FAILED (-2) loading 'app://-'
    at rejectAndCleanup (C:\Users\david\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\navigation-controller.js:72:21)
    at WebContents.stopLoadingListener (C:\Users\david\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\navigation-controller.js:113:9)
    at WebContents.emit (events.js:194:13) errno: -2, code: 'ERR_FAILED', url: 'app://-' }

## What did i do
``` js const serve = require("electron-serve");
const loadURL = serve({ directory: "./build" });

app.on("ready", async () => {
  win = new BrowserWindow({
    width: 800,
    height: 600,
    title: "POSine",
    autoHideMenuBar: true,
    show: false,
    webPreferences: {
      nodeIntegration: true
    }
  });
  win.maximize();
  await loadURL(win)
    .then(data => {
      console.log(data);
    })
    .catch(error => {
      console.log(error);
    });

  win.on("closed", () => {
    win = null;
  });
});
```
## what I spected
a window with the static files 

## what i actually got
a blank window with the error above in the terminal

Please if someone could help me with this

**Comment by mendoza** [comment]
Got news
## What I changed
```js 
let createWindow = async () => {
  await app.whenReady();
  mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    title: "POSine",
    autoHideMenuBar: true,
    show: false,
    webPreferences: {
      nodeIntegration: true
    }
  });

  mainWindow.maximize();
  await loadURL(mainWindow);
  // await mainWindow.loadURL("app://-");

  mainWindow.on("closed", () => {
    mainWindow = null;
  });
};

app.on("ready", createWindow);
```
I added the ```app.whenready()```  that the example on the main README says.
it works i have some problems with images but its all mine, sorry for that
